### ISSUE TITLE
Make undertow hostname configurable

### ISSUE THREAD

**Issue by stefanroeck** [http4k/http4k#1192]
Current implementation of undertow binds the http listener to all network interfaces `0.0.0.0`:
https://github.com/http4k/http4k/blob/ddf7d30eefddae7c1e37682742e3f7b4f334b2f6/http4k-server/undertow/src/main/kotlin/org/http4k/server/Undertow.kt#L46

It would be nice to have this configurable e.g. to be able to restrict the service to be accessible from localhost only for security reasons.

**Comment by daviddenton** [comment]
We decided very specifically to avoid any kind of Server Config wherever possible (due to the myriad of options available), but to make it easy and simple for people to write their own versions with the minimum amount of copied code. So from that perspective am afraid it’s a no. Making detailed generic interfaces (like a builder) is just not really worth it when people don’t really tend to change much and if they want custom configuration then they’ll already write their own ServerConfig version anyway.

However, we are very happy to accept PRs on how to reduce the boilerplate required by extracting common code from the various current implementations (like the various handler classes that already exist).

😄
