### ISSUE TITLE
BiDiBodyLens Does Not Support Generic Type

### ISSUE THREAD

**Issue by asleson** [http4k/http4k#1240]
I'm using Moshi and Kotshi as the JSON toolkits for http4k.

I have a parameterized type that looks like this:

```
@JsonSerializable
data class PaginatedResults<T>(
    val items: List<T>,
    val id: String,
)
```

And an example of the parameterized type:

```
@JsonSerializable
data class Person(
    val firstName: String,
    val lastName: String,
)
```

If I have an instance of `PaginatedResults`:

```
val paginatedResults = PaginatedResults(
    items = listOf(
        Person(
            firstName = "Testy",
            lastName = "Tester",
        )
    ),
    id = "abc123",
)
```

And I have an instance of `ConfigurableMoshi` and I try to do either of these operations:

```
// moshi is an instance of ConfigurableMoshi
val asJsonString = moshi.asFormatString(paginatedResults)
val asObject = moshi.asA<PaginatedResults<Person>>(asJsonString)
```

These operations will fail with an error that looks something like this:

```
PaginatedResults is generic and requires you to specify its type
java.lang.IllegalArgumentException: PaginatedResults is generic and requires you to specify its type
arguments. Don't request an adapter using Type::class.java or value.javaClass but rather using
Types.newParameterizedType.
	at se.ansman.kotshi.KotshiUtils.getTypeArgumentsOrFail(KotshiUtils.kt:20)
```

The error is [coming from Kotshi](https://github.com/ansman/kotshi/blob/main/api/src/main/kotlin/se/ansman/kotshi/KotshiUtils.kt#L18).  Digging into it a little bit, it looks like the `Type` that is passed to the Moshi adapter is a `Class` not a `Type`.

HOWEVER:  if I use these operations on the `Moshi` object, which was created using the same `Moshi.Builder` as the `ConfigurableMoshi` above, then it works as expected:

```
// the moshiBuilder instance is the same one used to build the ConfigurableMoshi instance above
val adapter = moshiBuilder.build().adapter<PaginatedResults<Person>>()
val asJsonString = adapter.toJson(paginatedResults)
val deserialized = adapter.fromJson(asJsonString)
```

Since the above lines work, that suggests that `Moshi` is working as expected.  However, same object instance cannot be serialized/deserialized when going through an instance of `ConfigurableMoshi`.

I originally saw the problem when I created and used a lens in an HTTP request:

```
// moshi is the instance of ConfigurableMoshi
val paginatedResultsPersonLens = moshi.autoBody<PaginatedResults<Person>>().toLens()
```

It's an HTTP `GET` that tries to return an instance:

```
Response(OK).with(paginatedResultsPersonLens of persons)
```

This fails with the same error shown above.  I isolated the problem in a small unit test.

Is this a bug, or am I doing it wrong?

Thank you!!!

**Comment by daviddenton** [comment]
Have you got the unit test for us to play with it? That would be really helpful TBH 🙃

**Comment by daviddenton** [comment]
On further inspection - it may be that the calls that are working are using reflection under the covers (which I presume you don't want to use since you are using kotshi). Have you excluded Kotlin reflect from your classpath?

In [moshi](https://github.com/square/moshi/blob/d5893da94be51dcc0c6c535a9b37737a6d41a539/moshi/src/main/java/com/squareup/moshi/Moshi.kt) the call you've pointed out...
```public inline fun <reified T> adapter(): JsonAdapter<T> = adapter(typeOf<T>())```

... where typeof is coming from kotlin reflect ```import kotlin.reflect.typeOf```.

AFAICT the http4k version uses a different path through the Moshi API which looks up the adapter differently without reflection using the inlined reified class. This may account for the change in behaviour. We obviously don't want to rely on reflection.

It might be worth investigating Kotshi and polymorphism more closely - it is a bit of a tricky subject (and we try to avoid polymorphic types where possible without using the standard Moshi annotations.

For the moment I'm going to close this because I'm not sure it's something we can fix in or code - but if you find something different where we can improve then please feel free to open it again.  😄

**Comment by asleson** [comment]
Hello!  Thank you for taking a look!  I was able to extract my small example from the larger project in which I was working, and the behavior is still there.

I have attached a small project that demonstrates the problem, and also the pattern that works.  There is a Kotest `MoshiTests` file that has two tests:  one that fails, and one that succeeds.  

It's as minimal example as I can create.

Could you please take a quick look?  If there is nothing that can be done, no worries.  If it's something with excluding `kotlin-reflect` how can I do that?  Because if I do that, then Kotest doesn't even run, and I don't think other things will either.

Thank you!!!
[http4k-moshi-bug.zip](https://github.com/user-attachments/files/18136568/http4k-moshi-bug.zip)

**Comment by asleson** [comment]
(BTW I can't see how to re-open this issue)

**Comment by daviddenton** [comment]
fundamentally the reason to use kotshi is to avoid reflection entirely. If you need it then there is questionable value in having the adaptor generation at all imho - just fall back to using polymorphic moshi adapters using the standard Moshi annotations and it should work. Then you can drop the adapter generation entirely or just for the polymorphic classes?

The reopen button should be below thr comment box. 👇🏼

**Comment by asleson** [comment]
Right, the reason I want to use Kotshi is to avoid reflection entirely.  Eventually I want to try to compile this to a native Amazon image.

My app isn't using any reflection, at least none that I've written.  I'm just saying that if I do something like in the `build.gradle.kts` file (I'm doing this from memory as I don't have the code here):

```
configurations.all {
    exclude("org.jetbrains.kotlin:kotlin-reflect"
}
```

then my Kotest tests won't even run.

Just so I'm on the right page as I don't want to be a pest:  given the small test case that I attached in the previous comment, is this a case that http4k can investigate?  Or are you sure there's nothing that can be done?  If there's nothing to be done on the http4k side, that's cool, just so I know and can proceed according.  But the attached test case is small and simple and, like you said, might be really helpful.  🙂 

Thank you so much for your help!!

And I must be blind, because I don't see a Re-Open Issue button anywhere here!  (See attached screenshot)
<img width="1008" alt="Screen Shot 2024-12-15 at 10 41 10 AM" src="https://github.com/user-attachments/assets/57784401-c1e5-49ba-8457-452f644503cc" />

**Comment by daviddenton** [comment]
Checking out the example a bit more, the problem here is actually **Java** reflection and not Kotlin reflection.  

We cannot switch our Moshi to use the ` moshiBuilder.build().adapter<PaginatedResults<Person>>()` version inside http4k because that means that all calls would use Java reflection. 

Furthermore - I don't think you will be able to compile to GraalVM while using that method anyway - although it's worth double checking that.

Re github: I didn't actually know that only we have the ability to reopen issues! I've been working under that assumption for a long time! 🙃

**Comment by asleson** [comment]
In both cases I can see that it's using the `KotshiApplicationJsonAdapterFactory`, which of course is generated code.  The difference is that when it fails, the `Type` that i sent to the `KotshiApplicationJsonAdapterFactory` is a `Class` which doesn't have enough information for the parameterized type.  When it works, the `Type` that i sent to the `KotshiApplicationJsonAdapterFactory` is a `ParameterizedType`, which has the type info it needs.  Weird that it works that way when going through the http4k layer.

Regardless, I'll work around it to avoid the parameterized type.  Thank you so much for your helpful explanation!
![Screenshot 2024-12-16 at 5 47 52 AM](https://github.com/user-attachments/assets/9c060903-e622-4b1d-afc6-fe4bfa41a1e0)
![Screenshot 2024-12-16 at 5 49 13 AM](https://github.com/user-attachments/assets/22ea8ad8-e38b-4365-8772-2cd4ff63392e)
