### ISSUE TITLE
Any way to stream data in the response ?

### ISSUE THREAD

**Issue by fzakaria** [http4k/http4k#133]
Curious if there's a good functional paradigm to stream data in the response.
Maybe instead of _fn(request) -> response_ do something like _fn(request, response, next)_

**Comment by s4nchez** [comment]
@fzakaria we allow streaming data in the response by allowing the body to hold an `InputStream`. That allows handling big/slow responses if that's what your app needs, but still keeps the core abstractions of the library simple for the vast majority of cases.

The `fn(request, response, next)` approach assumes request/response as mutable objects you can partially read/write. We'd like to avoid that because it makes your code harder to reason about and debug.

Instead, we choose to represent HTTP messages as immutable data structures by default and use two main abstractions (`HttpHandler =  (Request) -> Response` and `Filter : (HttpHandler) -> HttpHandler`) for both serving and consuming HTTP.

I hope that answers your question. If you have a specific use case you'd like us to consider, please let us know.

**Comment by fzakaria** [comment]
Looking at the code: https://github.com/http4k/http4k/blob/master/http4k-core/src/main/kotlin/org/http4k/core/http.kt

It's just stored as a buffer in memory -- I'm not sure that counts as "streaming" because any large file would fill the buffer and cause OOM?

**Comment by s4nchez** [comment]
Notice that the `Body` exposes the stream directly. That's used by the `StreamBody` in the cases one would like to stream the content, rather than build it entirely before sending it over the wire.

You can check out the streaming tests to see it all in action: https://github.com/http4k/http4k/blob/master/http4k-core/src/test/kotlin/org/http4k/streaming/StreamingContract.kt

We have http4k running with streaming in various projects, handling files that are larger than the JVM heap and can assure it works :)
