### ISSUE TITLE
OpenApi does not render a correct request body description

### ISSUE THREAD

**Issue by reik-wargaming** [http4k/http4k#198]
Here is a specification for describing request bodies: https://swagger.io/docs/specification/2-0/describing-request-body/

This code [here](https://github.com/http4k/http4k/blob/69e45034785f28c3c77f2ffad8188d9e603ec991/http4k-contract/src/main/kotlin/org/http4k/contract/OpenApi.kt#L56) renders the `type` without a parent `schema` (if schema  == null). This will render the UI without a text input field for the body, impacting most POST and PUT routes if you want to send a test request.

**Example**

actual

	{
		"in": "body",
		"name": "body",
		"required": true,
		"type": "object",
		"description": "Some JSON"
	}

expected

	{
		"in": "body",
		"name": "body",
		"required": true,
		"schema": {
			"type": "object",
		}
		"description": "Some JSON"
	}

**Comment by daviddenton** [comment]
I think this is actually working correctly - but the API might not actually be particularly clear.

This code generates a working Swagger API:

```kotlin
data class UserEntry(val username: String, val goingIn: Boolean, val timestamp: Long)

object Echo {
    private val message = Body.auto<UserEntry>().toLens()

    fun route(): ContractRoute =
            "/echo" meta {
                receiving(message to UserEntry("bob", true, 12))
                returning("Exit granted" to Response(OK).with(message of UserEntry("bob", true, 12)))
            } bindContract POST to { Response(OK).with(message of message(it)) }
}```

and the appropriate swagger JSON snippet is here:
```
"parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/object1745923380"
            }
          }
        ]
```

I suspect you're using `body` instead of `receiving` - am going to investigate the presence of both `body` and `receiving` and see if body can be removed.

**Comment by daviddenton** [comment]
Further, I am changing the API slightly. I have hidden the `body` property - this is now accessed through the overloaded `receiving` method (which you have 2 options for using - one WITH an example body, and one WITHOUT an example body). Only if an example value is used
 will the JSON schema be generated. Hopefully this will be clearer now.

Slightly breaking the API because this mistake was vey easily done - we even made this exact error in the documentation and example project!

Thanks for the report @reik-wargaming  😄

**Comment by reik-wargaming** [comment]
@daviddenton would it be possible to change to something this in `renderMeta`:
 
	schema?.let { "schema" to it.node } ?: "schema" to mapOf("type" to string(it.paramMeta.value))

This will render a valid `schema` element, even if the fallback is used. Maybe I miss something?

**Comment by daviddenton** [comment]
I've properly fixed this now. releasing in 3.103.1. Much confusion was caused by the Swagger UI being out of date and buggy.
