### ISSUE TITLE
Status.equals fails to distinguish between CONNECTION_REFUSED and UNKNOWN_HOST

### ISSUE THREAD

**Issue by gowlin** [http4k/http4k#209]
The comparison on Statuses is based on the code and whether it is client generated. This makes Status.UKNOWN_HOST == Status.CONNECTION_REFUSED

**Comment by daviddenton** [comment]
This is actually a deliberate design decision that we've taken in the clients, so that they try to always return an HTTP status code as opposed to throwing exceptions wherever possible.

The fact that the equality doesn't take the message into account allows people to define their own (more helpful - for example in the CatchLensFailure Filter) status messages and still check for the overall status - which (from a client caller perspective) is SERVICE_UNAVAILABLE regardless of the reason it occurred. 

We're suffering here from a lack of codes in the HTTP protocol to describe all the scenarios.

It is a wrinkle that we're aware of and thanks for raising it. If we can improve it we're happy to look at it again if we can make sure that the expected use cases aren't affected. That said, I'll close this for now until then. 😄
