### ISSUE TITLE
support netty ssl

### ISSUE THREAD

**Issue by icode** [http4k/http4k#220]
support netty ssl context, or example code

**Comment by daviddenton** [comment]
The model for the http4k server backends is to not provide a comprehensive modelling or documentation of everything that can be done because every use-case is probably slightly different so we could never hope to cover everything. Instead, we provide the `ServerConfig` interface along with a default implementation, and encourage users to write their own custom version for their own purposes. For Netty, this would involve reusing the `Http4kChannelHandler`. You can see the default implementation [here](https://github.com/http4k/http4k/blob/a6d72a3ddce6a788d22a885eeebf4fc7a90c0979/http4k-server-netty/src/main/kotlin/org/http4k/server/Netty.kt)

[This](https://github.com/ThilinaManamgoda/netty-https) seems to be a good example of the kind of setup you'd be looking for - just swap out their custom Handler with the Http4k one and you should be good to go. :)

So going to close this for now, because it's actually more relevant to the subject of "how to configure netty" than a http4k specific issue. Alternatively, if you'd like to write a cookbook article about how to achieve it, then feel free to donate one and we can include it in the site.
