### ISSUE TITLE
/ in fixed paths after a path param does not match 

### ISSUE THREAD

**Issue by ctruchi** [http4k/http4k#221]
Hi,

In the following example, you cna see what is going on.

```kotlin
import org.http4k.contract.ApiInfo
import org.http4k.contract.OpenApi
import org.http4k.contract.bind
import org.http4k.contract.contract
import org.http4k.contract.div
import org.http4k.core.Body
import org.http4k.core.ContentType
import org.http4k.core.Method
import org.http4k.core.Request
import org.http4k.core.Response
import org.http4k.core.Status
import org.http4k.core.with
import org.http4k.format.Jackson
import org.http4k.lens.Path
import org.http4k.lens.string
import org.http4k.server.Netty
import org.http4k.server.asServer

fun main() {
    val app = "/api" bind contract(OpenApi(
            ApiInfo("API", "v1"), Jackson),
            "/docs",
            "/path" / Path.of("id") / "dont/match" bindContract Method.GET to dontMatch(),
            "/path" / Path.of("id") / "does" / "match" bindContract Method.GET to doesMatch())

    app.asServer(Netty(8100)).start()
}

private fun dontMatch() = { _: String, _: String ->
    { _: Request ->
        Response(Status.OK).with(Body.string(ContentType.TEXT_PLAIN).toLens() of "YEAH !")
    }
}

private fun doesMatch() = { _: String, _: String, _: String ->
    { _: Request ->
        Response(Status.OK).with(Body.string(ContentType.TEXT_PLAIN).toLens() of "YEAH !")
    }
}
```

A request on `http://localhost:8100/api/path/id/dont/match` returns a 404 whereas a request on `http://localhost:8100/api/path/id/dont/match` answers correctly.

OpenApi generates documentation for both routes though.

After some investigation, it seems 3 path params are expected for `"/path" / Path.of("id") / "dont/match"` instead of 2.

Hope this can help.
I am using http4k 3.131.0

**Comment by daviddenton** [comment]
What you're seeing here is a bit of a quirk that trailing fixed paths cannot have / characters in them. This IS inconsistent (as you can have one in the prefix section), but it's ultimately due to the way in which the path parameters are matched - the path is split on "/" and then each individual section compared for compatibility. 

Unfortunately we can't make this restriction via the type system (because passing a fixed path parameter on an `ContractRouteSpecN` always resulting in a `ContractRouteSpecN+1` being returned (regardless of the number of / characters in the passed string). We can however, put in a guard to explode if a / character is passed, so we can make that change.

Hope that's good enough 😄

**Comment by ctruchi** [comment]
Thanks for your answer, I was feeling it was something like this :)

Your solution seems good enough for me. I didn't look in http4k doc if "/" are forbidden in trailing fixed paths but it should be a good thing.

P.S : Thanks for http4k, I have a lot of fun with it
