### ISSUE TITLE
How to implement redirect and forward?

### ISSUE THREAD

**Issue by davioooh** [http4k/http4k#236]
Sorry, but I can't find an example in docs explaining how to implement request redirect or forward in routing config.

Can you provide me with a working snipped of code?

Thank you very much.

David

**Comment by daviddenton** [comment]
Assuming you don't mean just creating a client-side redirect (3XX), then because everything is based on anonymous functions, there isn't an internal routing facility built in to http4k. 

Pattern 1: You'll need an object reference to the redirected HttpHandler and you can then call that handler based on the condition. I'd probably extract the redirected handler to a higher level in your app stack and then pass it down into both places (original and the filter).

Pattern 2: return a specific type of response (say a 301 with a particular header set) from your original handler, and then add a Filter around the outside of your entire app to detect that response was returned and then reroute the request at the top layer to the new location (by rewriting and resubmitting the request).

For more online help - best to use the kotlinlang slack - you can get much more immediate help there.
