### ISSUE TITLE
Echo example won't work for me, or any request that uses body.auto lens...

### ISSUE THREAD

**Issue by raxelz** [http4k/http4k#246]
I have been trying to make this automatic marshaling and lenses to work for any request that uses body.auto lens and it won't work... please help me out, I tried for hours :(

When using the echo example: https://github.com/http4k/http4k/blob/master/src/docs/guide/modules/contracts/example.kt

`
// this route uses auto-marshalling to convert the JSON body directly to/from a data class instance
fun echoRoute(): ContractRoute {

    data class NameAndMessage(val name: String, val message: String)

    // the body lens here is imported as an extension function from the Jacskson instance
    val body = Body.auto<NameAndMessage>().toLens()

    // this specifies the route contract, including examples of the input and output body objects - they will
    // get exploded into JSON schema in the OpenAPI docs
    val spec = "/echo" meta {
        summary = "echoes the name and message sent to it"
        receiving(body to NameAndMessage("jim", "hello!"))
        returning(OK, body to NameAndMessage("jim", "hello!"))
    } bindContract POST

    // note that because we don't have any dynamic parameters, we can use a HttpHandler instance instad of a function
    val echo: HttpHandler = { request: Request ->
        val received: NameAndMessage = body(request)
        Response(OK).with(body of received)
    }

    return spec to echo
}

 val contract = contract {
        renderer = OpenApi3(ApiInfo("ID-Lite API", "1.0", "Connecting legacy and new accounts"), Jackson)
        descriptionPath = "/swagger.json"

        routes += echoRoute()
    }

    val handler = routes(
        "/" bind filter.then(contract),
        "/static" bind NoCache().then(static(Classpath("idlite/api_skeleton"))),
        "/api/v1" bind contract
    )
`

**I start server:**

`
ServerFilters.Cors(CorsPolicy.UnsafeGlobalPermissive).then(handler).asServer(Netty(8000)).start()
`

**I receive:**
{
    "message": "Missing/invalid parameters",
    "params": [
        {
            "name": "body",
            "type": "body",
            "datatype": "object",
            "required": true,
            "reason": "Invalid"
        }
    ]
}

**Comment by daviddenton** [comment]
Sorry! This is completely our error in the example, due to us not actually calling the echo (only displaying the swagger docs.

The problem seems to be occurring because the `NameAndMessage` class is private inside the echoRoute function - if you move it outside to the top scope then it works.

Have fixed it now in the docs and added an example of calling the echo to make sure the example runs properly.

Sorry again - and thanks for raising it instead of giving up :)

If you need any more (immediate) help or advice, a good place to go is the #http4k channel in the KotlinLang slack.
