### ISSUE TITLE
Question about org.http4k.core.Status

### ISSUE THREAD

**Issue by ivoanjo** [http4k/http4k#262]
Hello there 👋!

While working on a simple filter to map exceptions to errors, I ran into the problem of creating an instance of `org.http4k.core.Status` given an http status code (that can be added via an annotation to the exception).

Specifically, what is the `description` argument supposed to contain? Creating a `Response(Status(404, "not sure what this does"))` seems to work, and the `description` does not seem to be used anyway.

I was expecting to find something like a `Status.fromCode(404)` -- would this make sense as an addition, or am I using this wrong?

As usual, thanks for http4k :smile:

**Comment by s4nchez** [comment]
@ivoanjo That description is called "reason" in the HTTP spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html

It does get sent over the wire, and is visible by HTTP clients and browsers. It's useful for debugging as it may be simpler than the actual response (json/HTML/XML). 

For instance, if you're using our basic routing (via `routes(..`), we return a 404 with specific reason when the route is not found (as opposed to a 404 produced by an existing route):

So something like:

```kotlin
    val routes = routes("/foo" bind Method.GET to {Response(Status.OK)})
    println(routes(Request(Method.GET, "/bar")))
```

Produces: 

```
HTTP/1.1 404 Route not found
```

In your scenario, perhaps the exception type could be in the description of the status, and extra information (e.g message + stacktrace) could be in the body. If you're logging requests in a searchable database, that information can be useful to find particular classes of error.

I hope this helps, otherwise feel free to ask more questions.

**Comment by ivoanjo** [comment]
Thanks a lot for clearing it up @s4nchez :)

Always learning! I somehow thought that the messages were also standard for the well-known status codes, and thus they would not be expected to change -- only for custom status codes. Clearly my assumption was way off, and with `418` the webserver is allowed to not be a teapot.

I've realized that also what threw me off is that I was using `SunHttp` for testing, and clearly `SunHttp` does not support custom messages, so when I supplied a custom one, nothing happened. Works fine with `Jetty`.

Have a great evening!
