### ISSUE TITLE
Confusing error messages from lens when using custom types?

### ISSUE THREAD

**Issue by ivoanjo** [http4k/http4k#263]
Hello there!

I have a `Path` lens with a custom type (similar to the examples in [the documentation](https://www.http4k.org/guide/modules/core/)). I wanted some extra validations on my custom type, and throw an exception when they fail.

This correctly makes the lens fail, but the resulting error message is really confusing, as it just says `path 'field' must be a string`, rather than exposing the upstream error.

Example:

```kotlin
#!/usr/bin/env kscript
//DEPS org.http4k:http4k-core:3.163.0

import org.http4k.core.*
import org.http4k.filter.*
import org.http4k.routing.*
import org.http4k.lens.*
import org.http4k.core.Status.Companion.OK
import org.http4k.core.Method.GET
import org.http4k.filter.ServerFilters

data class CustomType(val value: String) {
    init { if (value == "foo") throw IllegalArgumentException("Sorry, no foos please")}
}

val requiredCustomQuery = Path.map(::CustomType, { it.value }).of("name")

val app: HttpHandler = ServerFilters.CatchLensFailure().then(routes(
    "/greet/{name}" bind GET to { req: Request ->
        val custom = requiredCustomQuery(req)
        Response(OK).body("hello ${custom}")
    })
)

val inMemoryResponse: Response = app(Request(GET, "/greet/foo"))
println(inMemoryResponse)
```

Output:

```
HTTP/1.1 400 path 'name' must be string
```

What I expected:

I expected the exception to be included in the message, e.g. something like `path 'name' is invalid: Sorry, no foos please`.

Am I missing something? Looking at the lens mechanism, there doesn't seem to be a clear way to configure this, other than basically changing the `CatchLensFailure` to ignore the `Failure` object.

It seems like if I could provide my own `meta` this could maybe be supported, but there doesn't seem to be a way to use my own `Meta` with a `Path` lens..:?

**Comment by daviddenton** [comment]
We deliberately don't expose the underlying stack for security, but it is available in the LensFailure class - so if you customise CatchLensFailure you can get at the reason. An example doing this in the cookbook would penalty help here.

With regards to the "not a string" message, we can try to look at making it better, but due to the way in which lenses are constructed it is difficult to customise.

Thanks for the comment though - these are really helpful when prioritising.

**Comment by ivoanjo** [comment]
Thanks for the feedback! Yeah, I ended up customizing the `CatchLensFailure`:

```kotlin
ServerFilters.CatchLensFailure { lensFailure ->
    badRequest("${lensFailure.failures.map { "${it.type} ${it.meta.name}" }.joinToString(", ")}: ${lensFailure.cause!!.message}")
}
```

where `badRequest` just basically writes the message in the body of the response.

(It's not directly related to this issue, but I was also a bit surprised that the `CatchLensFailure` by default only modifies the server `description` that gets sent along with the status, not the response, as at least `SunHttp` and lambda don't propagate these).

> With regards to the "not a string" message, we can try to look at making it better, but due to the way in which lenses are constructed it is difficult to customise.

Perhaps when a custom type is used, http4k at least could fall back to a more generic `path 'foo' is not valid' or similar message? That way, even if opaque, at least it wouldn't be confusing/misleading.

**Comment by daviddenton** [comment]
As of the last release a few days ago, `CatchLensFailure` now has access to the underlying cause of the failure (exception), so hopefully messages can be crafted on an as needed basis.

Hopefully this is good enough. I'm going to close this now, but feel free to reopen if the changes don't give enough control. 😄

**Comment by ivoanjo** [comment]
Thanks, I'll give it a try and report back if I have any issues! :)

**Comment by 2x2xplz** [comment]
> We deliberately don't expose the underlying stack for security, but it is available in the LensFailure class - so if you customise CatchLensFailure you can get at the cause. **An example doing this in the cookbook would definitely help here.**

Hi, I think this is overdue. One of the primary tenets of http4k is "**5. Absolutely no magic involved**" and while Lenses may not technically be "magic," they sometimes feel like it -- they handle the conversion of raw HTTP data into objects and back, under the hood and without any logging or explanation of why a particular request is malformed. Don't get me wrong, they are very useful but I believe logging and transparency should be easily enabled (something like `CatchLensFailure(showStack = true, logRawRequest = true)` ), or at least an example of a custom replacement function (difficult to write due to the complex function signature). Thank you 👍

**Comment by daviddenton** [comment]
> I believe logging and transparency should be easily enabled 
You can achieve this by using one of the `DebuggingFilters` and just composing it into the handler stack.

>(difficult to write due to the complex function signature).
Assuming you mean the custom function passed to the CatchLensFailure, the function signature is just `(LensFailure) -> Response`

Most people have problems with the JSON auto marshalling, but the underlying LensFailure cause actually contains a reasonable message. 

Here's a Gist with an example of all that stuff in one:
 
https://gist.github.com/daviddenton/a8b783af89e53c86d2b6de63f847e51c
