### ISSUE TITLE
Mention http4s in the readme?

### ISSUE THREAD

**Issue by Krever** [http4k/http4k#265]
Hey, it seems that http4k might be inspired by http4s at few spots and if so it would be nice to mention and link it from the readme. 

https://github.com/http4s/http4s

If I'm wrong and you have not seen the http4s before and not have taken inspiration from it then feel free to close this issue :)

**Comment by daviddenton** [comment]
Sorry - we have heard of http4s, but aren't familiar with how it works. The design for http4k definitely was inspired/stolen from various other frameworks though - notably UtterlyIdle (itself inspired by webfabric IIRC), finagle and fintrospect.

We pay homage to these in the rationale of http4k page - because we're definitely standing on the shoulders of others 😉: https://www.http4k.org/rationale/
