### ISSUE TITLE
Support AWS X-Ray

### ISSUE THREAD

**Issue by KushalP** [http4k/http4k#283]
http4k already supports Zipkin traces. It would be useful to support other distributed tracing services like AWS X-Ray.

**Comment by daviddenton** [comment]
These should be easy to implement via the same Filter mechanic that we use for RequestTracing. If you'd like to PR an implemention of the required Server and Client filters (inside the AWS module would be good). then we can look at merging those in. :)

**Comment by KushalP** [comment]
@daviddenton it looks like we're not using any of the AWS SDKs. Is this on purpose?

**Comment by daviddenton** [comment]
Absolutely on purpose. http4k provides a simple wrapper which will sign requests using the same algorithm as the AWS SDK - it works with all the services and the resultant JAR is 30k instead of 100 times that! 

By using Http4k clients instead of the SDK ones, we also get the ability to instrument out HTTP clients using the filter stacks.

Of course, there's nothing to stop people using the AWS SDK in their apps if they want, but we're not going to drag it in by default. :)

**Comment by daviddenton** [comment]
FYI, This is now possible using the OpenTelemetry module, with it's pluggable tracing propagators.  There is no standalone filter in the core though.
