### ISSUE TITLE
Support kotlinx.serialization

### ISSUE THREAD

**Issue by KushalP** [http4k/http4k#305]
It's common for teams to use a common serialisation approach with a core set of `data` classes.

[kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) can do a lot of the things that we need. Investigate ways to use this library as the serialisation/deserialisation method for things like JSON, CBOR, Protobufs, and Avro.

**Comment by s4nchez** [comment]
Thank you for the suggestion, @KushalP.

If you want to try and implement this new format approach, it should be a case of creating a new gradle module and implementing the [Json.kt](https://github.com/http4k/http4k/blob/master/http4k-core/src/main/kotlin/org/http4k/format/Json.kt) interface. We'd be happy to incorporate this new module.

**Comment by MrBergin** [comment]
I had a go at implementing the Json interface [back in October](https://github.com/MrBergin/http4k/tree/kotlinx-serialization) but ended up dropping it due to lack of time.

 It's by no means complete (even has some copy paste references to Argo / Jackson in the test folder). 

Just dropping this here in case it helps the person who picks this up :).

P.S. I got stuck fulfilling the JsonContract test `serializes object to json`, since KotlinxSerialization was wrapping the BigDecimal value in quotes.

**Comment by daviddenton** [comment]
@MrBergin that looks like a good start. Hopefully it will get picked up and finished off (or even by you! 😄)

**Comment by joscha-alisch** [comment]
I did have a go at this starting with the work @MrBergin did but also failed at getting BigDecimal to work.
At the moment it doesn't seem possible to customize the serialization in a way that allows serializing a BigDecimal without quotes. 

The only way (I can see) would be to more or less reimplement all their [serializers](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/json/JsonElementSerializer.kt), just to be able to include the proper serialization for BigDecimal [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/json/JsonElementSerializer.kt#L109-L128). Needless to say that this doesn't seem like a good idea ;)

This is also a (sadly closed) issue over at their repo: https://github.com/Kotlin/kotlinx.serialization/issues/368#issuecomment-462252860 

What do you think about their argument regarding the size of numbers @daviddenton @s4nchez ?

**Comment by daviddenton** [comment]
@joscha-alisch have you got a branch that would show where you've got up to? We could maybe provide a (semi) compliant version of the format lib (which always provides BigDecimals as Strings) and override the test case to expect this. This would be a limitation of the module, but might be useful to some people (since it looks unlikely to be fixed any time soon)... thoughts welcome! 😄

**Comment by joscha-alisch** [comment]
@daviddenton here you go: https://github.com/joscha-alisch/http4k/tree/kotlinx-serialization

I've gone ahead and overrode the corresponding test. Is that what you had in mind?

There is still some work to be done regarding the data class generation. I hope to get to it later today.

**Comment by daviddenton** [comment]
Yep - that's what I had in mind for the test. 🙃
