### ISSUE TITLE
Support SameSite cookies

### ISSUE THREAD

**Issue by nlochschmidt** [http4k/http4k#340]
Afaics there is currently no support for setting the `SameSite` attribute for cookies in http4k. 

Would be nice to have a dedicated method for that and probably add the three options `None`, `Strict` and `Lax` as an enum.

I'd even go so far and make `Lax` the default for Cookies as recommended in [1]. Would love to know your opinion on that.

[1]: https://scotthelme.co.uk/csrf-is-really-dead/

**Comment by danielwellman** [comment]
I've made an attempt at adding this support to http4k, see #359.  I made SameSite an enum value but did not set a default if not present because today some browsers inconsistently interpret `SameSite=None`. In those cases it's better to omit the attribute rather than set one; this primarily affects third-party cookies. This means you need to either use two sets of cookies or inspect the request's user agent string and alter the SameSite value of the cookie (not to mention that starting in Chrome 80, all SameSite=None cookies must also be Secure!). See this [web.dev article](https://web.dev/samesite-cookie-recipes/) and the [Chromium list of known incompatible clients](https://www.chromium.org/updates/same-site/incompatible-clients).

Some questions I had on style:
- I made the `SameSite` enum an inner class of `Cookie`, which means clients would need to explicitly import the class if they want to say `Cookie(... sameSite=Lax)` vs. `Cookie(... sameSite=Cookie.SameSite.Lax)`.  What's your preferred way of handling this?
- Parsing an unknown SameSite value (not represented in the enum list) will silently return null, rather than thrown an IllegalArgumentException.  What do you prefer?

I'm still developing my understanding of Kotlin style and am very new to http4k, so please do let me know of any suggestions you have.

**Comment by daviddenton** [comment]
Hey - thanks for the contribution! Generally looks good - I'm not familiar with SameSite so want to read around it a bit.

For your questions:
1. I'd represent SameSite on the top level - we are in the cookie package so that shouldn't be an issue - I can do this after merging it.
2. We don't want to throw in the case of an unknown value - let's start with the null and see how it goes 😄 

Thanks again!

**Comment by daviddenton** [comment]
This will go out in 3.227.0

**Comment by nlochschmidt** [comment]
Thanks!
