### ISSUE TITLE
Dependency injection in http4k

### ISSUE THREAD

**Issue by nicholsonthebest** [http4k/http4k#401]
I am currently evaluating whether http4k is the framework I want to be using for my microservices.

Is there any documentation explaining how dependency injection should/can be handled in http4k? Similar to these:
- https://ktor.io/samples/feature/guice.html
- https://ktor.io/samples/other/di-kodein.html

**Comment by daviddenton** [comment]
The project doesn't have any guides written for integration with DI frameworks. This is for a couple of reasons:

1. There was a conscious decision made to not document anything integrations with other APIs that we don't support, because we would end up documenting the world - logging, DI, database code, messaging brokers.... :)
2. http4k is so simple that it should be a doddle to integrate with anything - it's just standard code with no magic. Hence, anyone with a passing knowledge of a DI framework should be able to instrument their http4k apps. And if this is too hard then that's possibly a signal...  ;)
