### ISSUE TITLE
Api Contract and Jackson PropertyNamingStrategy

### ISSUE THREAD

**Issue by mattbroekhuis** [http4k/http4k#404]
How can I use snake case property naming strategy with the contract module?
On a data class with `carrierName` as a property, whenever I try to use it I get

`org.http4k.contract.openapi.v3.NoFieldFound: Could not find carrier_name`

`val contract = contract {
      renderer = OpenApi3(ApiInfo("My Api", "v1.0"), ConfigurableJackson(snakeCaseMapper))
      descriptionPath = "/swagger.json"
      routes += module.searchControllers.allRoutes()
    }`

**Comment by daviddenton** [comment]
Assuming this is blowing up when attempting to render the OpenAPI Json, this should work - the problem may be in the JacksonJsonNamingAnnotated strategy, but that requires that the data class in question is annotated as opposed to the entire mapper. See this test for an example: `JacksonJsonNamingAnnotatedTest`. So that is a workaround for the moment.

It doesn't on the face of it look like we support global property naming strategies (other than the default) at the moment.  Not sure how easy this would be to implement currently - would require a bit of digging and then a custom FieldRetrieval class created.

**Comment by mattbroekhuis** [comment]
Yeah when I try and access the swagger.json it happens. Only once I believe, seems like it is lazily constructed and then cached. 

I had tried annotating the classes with the naming strategy of snake case explicitly, but I got the same error. Ok maybe I’ll get some time this next week to look deeper. Thanks for the cool library.

**Comment by daviddenton** [comment]
I've stuck in a fix so this should work now. Releasing it shortly in 3.245.0

**Comment by mattbroekhuis** [comment]
thanks!
