### ISSUE TITLE
Adding headers (e.g. content-disposition) for static resources?

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#445]
When using static resources documented here: https://www.http4k.org/guide/modules/core/

```kotlin
routes(
    "/static" bind static(Classpath("/org/http4k/some/package/name")),
    "/hotreload" bind static(Directory("path/to/static/dir/goes/here"))
)
```

Is it possible to somehow define content-type, content-disposition? I tried to add the header manually, but it doesn't seem trivial.

**Comment by s4nchez** [comment]
That’s a good point, @knyttl . 

I think that should be relatively trivial to implement as a filter that would look into the Request uri and based on file name + extension it would set the corresponding headers.

The only challenge is the file extension->content type mapping, I suppose.

**Comment by daviddenton** [comment]
We already have a mapping file of extension to content type in mime.types

**Comment by daviddenton** [comment]
Actually - we should already set the content type header in the static resource handler as that is exactly what the Mime types file is used for...

**Comment by knyttl** [comment]
> We already have a mapping file of extension to content type in mime.types

This helps for the content-type, but does it help for the content-disposition?

**Comment by s4nchez** [comment]
@knyttl would something like this be enough for your use case?

```kotlin
fun ContentDispositionAttachment() = Filter { next ->
        { request ->
            next(request).let { response ->
                when {
                    response.status.successful ->
                        response.header("Content-Disposition",
                            "attachment; filename=${request.uri.path.split("/").last()}")
                    else -> response
                }
            }

        }
    }
```
You'd apply this with something like `ContentDispositionAttachment().then(staticRoute)`

**Comment by daviddenton** [comment]
There is scope here to add a friendly Header to hander the directives. 

Extending the file - not sure about this. I don't think we'd want to make a default determination for each type, so it would probably have to be something like the above Filter so that users can apply it appropriately to their use-case. Maybe we could add a Filter that took a set of content types (or file extensions) that added the content disposition when those are hit?

**Comment by s4nchez** [comment]
Agreed. Unless we add `content-disposition: inline` as the default for static resources + a configuration mechanism to decide which files are `inline` vs `attachment`, I rather make this an independent `ServerFilter`. 

That’s because we can’t make any general assumption about the purpose of the resources being fetched by the client (e.g. file download vs a website asset)

**Comment by knyttl** [comment]
> You'd apply this with something like `ContentDispositionAttachment().then(staticRoute)`

This could work. Note if this is added to codebase, we would need the same for `ContentDispositionInline()`.

Thanks for prompt response!

**Comment by knyttl** [comment]
Also this might be helpful for adding caching headers for static resources.

**Comment by jenarros** [comment]
The PR #695 adds a simple filter based on https://github.com/http4k/http4k/issues/445#issuecomment-643135190 with the option to pass in a set of extensions so that only requests with those extensions will be considered for adding the Content-Disposition header.

**Comment by jenarros** [comment]
> > You'd apply this with something like `ContentDispositionAttachment().then(staticRoute)`
> 
> This could work. Note if this is added to codebase, we would need the same for `ContentDispositionInline()`.
> 
> Thanks for prompt response!

As `inline` is the default value for the header, I think it probably makes sense to simply omit it as most web servers do and only send the header when specifying a different value.
