### ISSUE TITLE
Create http4k-testing-kotest matchers

### ISSUE THREAD

**Issue by KushalP** [http4k/http4k#448]
There is already a matchers module for [hamkrest](https://github.com/http4k/http4k/tree/master/http4k-testing-hamkrest).

Is it worth creating a module to support [kotest](https://github.com/kotest/kotest)?

**Comment by daviddenton** [comment]
absolutely, feel free to PR it! :)

**Comment by nlochschmidt** [comment]
I'd love to see that as well and would be willing to provide a PR.

Not sure which direction is better here, but let me point out that kotest already has assertions for various libs (see [kotest-assertions](https://github.com/kotest/kotest/tree/master/kotest-assertions)) and http4k could be added there as well.

Maybe @sksamuel can chime in.

**Comment by daviddenton** [comment]
Thanks again @nlochschmidt . Either solution works for us - if there is prior-art keeping the matchers closest to kotest then maybe let's not break the pattern to keep things as discoverable as possible. If this does happen then please link in the PR here and we can also add a link somewhere in the docs.

**Comment by sksamuel** [comment]
In my opinion it is better to build them here because http4k is a large library and it's easier to keep in sync if it's part of the main project, whereas the only part of Kotest you would need to rely on is the Matcher interface (and that's not going to change).

The other assertion libraries we keep in Kotest are for things that are either ubiquitous (like jdbc matchers, json matchers) or for relatively small projects like klock and konform. And really both of those last two should have lived with the main project.

**Comment by sksamuel** [comment]
Also let me know if I can help in any way.

**Comment by daviddenton** [comment]
WFM! 😃
