### ISSUE TITLE
Query.enum<>() is not properly documented in OpenAPI

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#452]
When using following definition:

```kotlin
... meta {
    this.queries += Query.enum<EntityType>.required("targetEntityType", "Entity type interacted upon.")
    ...
}
```

Within OpenAPI the `Query.enum` is actually handled as `String` and the possible `enum` values are not listed:

<img width="566" alt="Screenshot 2020-06-29 at 23 42 54" src="https://user-images.githubusercontent.com/401107/86059105-63ac0280-ba62-11ea-8abf-da21870d80b4.png">

I am not sure if this is a missing feature or OpenAPI does not allow this?

**Comment by daviddenton** [comment]
Unfortunately for the non-body parts of a request, we don’t have the ability to determine enum types. This is because the enum is just a mapping of the input string value instead of being introspectable from the type system (as when creating the schema from the code). Without completely rewriting the lens system i don’t think it’s possible in an acceptable way that outweighs the benefit here.
