### ISSUE TITLE
Body.auto<foo>().toLens() seems to be broken in version 3.220.0

### ISSUE THREAD

**Issue by GlennHoran** [http4k/http4k#461]
Hi, 
I could very well be wrong here as I'm still fairly new to http4k, but when I follow the documentation to try to unmarshal json into an object, postman throws back "could not get any response". I've followed the docs here: https://www.http4k.org/guide/modules/json/ and here: http://http4k-data-class-gen.herokuapp.com to unmarshal {"value": "hello"} to a data class with one String variable called value in attempt to get things to work with a very basic example, but I can't get it to work. I've also wrapped things in a try catch block, but there's no exception thrown and debugging didn't reveal anything useful. I also made sure to manually import Jackson.auto as per the docs.

When I reverted from version 3.220.0 to version 3.110.0, everything seems to as expected. 

```
data class Foo(val value: String)

fun doAThing(): HttpHandler = { request ->
    try {
        val lens = Body.auto<Foo>().toLens()
        val extracted: Base = lens.extract(request)
    } catch (e: Exception) {
        println(e.message)
    }
  aFunction.fold(
            { Response(Status.INTERNAL_SERVER_ERROR).with().body(it.message) },
            { Response(Status.OK).with().body(" ${it.response()}") }
    )
}
```

**Comment by daviddenton** [comment]
Hmm - that's weird. I suspect that for some reason postman can't reach the server. But first off, is it possible to upgrade to 3.254.0 and try again?

If that doesn't work, which server backend are you running with? Can you post an entire bit of code including the server?

Try something like: 
```fun main() {
    val handler = { req: Request -> Response(Status.OK) } // put your handler here...
    DebuggingFilters.PrintRequestAndResponse().then(handler).asServer(SunHttp(8000)).start()
}```

**Comment by GlennHoran** [comment]
Hi David, Thanks for the quick response. 
I've sort of resolved the issue - I've updated to the latest version of Jackson (I was using version 2.9.8, and updated to 2.11.1) and things work as expected again with all the versions of http4k I've checked (3.110.0, 3.220.0, 3.254.0).

**Comment by daviddenton** [comment]
Aha - might it have been some type of clash on the classpath - strange that it didn't show? If you're not already, it might be a good idea to use a `ServerFilters.CatchAll()` (or equialent) around your application so that uncaught errors are reported correctly.

It's also a good job that you've upgraded anyway, especially with Jackson which has had a few CVEs open against it in the past. We try to keep on top of the versions where we can. BTW, `http4k-format-jackson` already brings in a (consistent) version of Jackson that it's expecting so there is no reason to list it separately unless there's a specific reason to.

I'll close this now. If you have further trouble then please reopen or find us on the Kotlin slack. :)

**Comment by GlennHoran** [comment]
I'll do that thanks! Thanks again for your help, best of luck
