### ISSUE TITLE
OpenApi schema field description

### ISSUE THREAD

**Issue by env0der** [http4k/http4k#464]
Is it possible to somehow specify a description of a field in OpenApi schema? Let's say I have a data class that models a response body and I would like to describe it's fields.

**Comment by env0der** [comment]
We are considering to use this library at work to implement an API, but we need a way to add descriptions to request/response model fields. I

'm willing to implement this feature and open a PR, but I would like to get some feedback from the maintainers if this change would be welcomed. I thought about implementing an annotation that you could use on a field level. Does it make sense?

**Comment by daviddenton** [comment]
This does make sense and happy to add it if we can come to a satisfactory solution, but it may well not be particularly straightforward to get right. :)

The solution is going to be along the lines of (working backwards from the output model):

1. Adding some type of metadata to `SchemaNode.Primitive` and `SchemaNode.Enum`. 
2. Moving back one level, this is going to involve changing `Field` to add the metadata
3. Changing the `SimpleLookup` `FieldRetrieval` instance to add this metadata to `Field` based on the annotation. You can see an example of this being done reflectively in `JacksonJsonPropertyAnnotated`.

**Comment by daviddenton** [comment]
Also - you can find a list of the valid OpenAPI3 field annotations at: https://swagger.io/specification/

I'd prefer not to tie the library directly to the OpenAPI spec, so if we could initially add just the ones that make sense, or maybe tie just the annotation to the spec (and use the field as a generic transport mechanism), that would be best.

**Comment by env0der** [comment]
Thanks for a quick reply @daviddenton!

How about using `@JsonPropertyDescription` annotation for this? Jackson documentation says the following:

```Annotation used to define a human readable description for a logical property. Not use by core databinding, but is used by JSON Schema generator for adding description in schema.```

**Comment by daviddenton** [comment]
Ah - if you're not worried about the machine-readable OpenAPI3-specific stuff like maxItems etc, then this should be simpler. Were you thinking about using the "description" field from OpenAPI3 to hold the description? Then you can just:

1. Add the description field (as String?, default to null) to Field - or maybe use a String,String map to provide freeform access for future proofing
2. Change SimpleLookup to take some type of metadataStrategy instead of just a renamingStrategy, and implement this in the Jackson-way when creating the `Field` instances.
3. You can then compose a new version of the FieldRetrieval using the new strategy (see jacksonExt.kt).

**Comment by env0der** [comment]
Yeah, we care about human-readable api docs. I will try implementing it as you suggest using `JsonPropertyDescription` annotation from Jackson to set the metadata on the field. Thanks for your help!

**Comment by env0der** [comment]
Opened a PR with discussed changes, please take a look.
