### ISSUE TITLE
Custom convertor for OpenApi

### ISSUE THREAD

**Issue by knyttl** [http4k/http4k#500]
I am trying to document response of type `com.google.cloud.Timestamp`, but once I try to see the Swagger doc, it raises:

```
org.http4k.contract.openapi.v3.NoFieldFound: Could not find seconds in 2020-10-16T20:52:43.337000000Z
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1.invoke(FieldRetrieval.kt:17) ~[http4k-contract-3.251.0.jar:?]
	at org.http4k.contract.openapi.v3.FieldRetrieval$Companion$compose$1.invoke(FieldRetrieval.kt:9) ~[http4k-contract-3.251.0.jar:?]
	at org.http4k.contract.openapi.v3.AutoJsonToJsonSchema.toObjectSchema(AutoJsonToJsonSchema.kt:64) ~[http4k-contract-3.251.0.jar:?]
```

1. Maybe the exception message can be improved?
2. I googled, read docs, but couldn't find how to solve this. Is this documented somewhere?

I appreciate any hints on this. Thanks.

**Comment by daviddenton** [comment]
http4k does cover all of the standard JVM + http4k primitives, but we can't cover everything. 😄 

For custom converters, you just need to implement your own version of Jackson and add the conversion explicitly. Then all the references to `Body.auto` will need to be changed to import your new method instead of the `Jackson.auto`

Guide is here: https://www.http4k.org/cookbook/custom_json_marshallers/

Closing this - please reopen if anything isn't clear.

**Comment by knyttl** [comment]
Thanks! 

I am trying following:

```
fun firestoreTimestampOf(value: String) = Instant.parse(value).toFirestoreTimestamp()

fun firestoreTimestamp() = BiDiMapping(::firestoreTimestampOf, Timestamp::toString)

object CustomJackson : ConfigurableJackson(KotlinModule()
    .asConfigurable()
    .withStandardMappings()
    .text(firestoreTimestamp())
    .done()
    .deactivateDefaultTyping()
    .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
)
```

I can now confirm the timestamp is correctly formatted with the `.toString()` as specified above.

However the openapi error didn't disappear: Could not find seconds in 2020-10-16T20:52:43.337000000Z

Isn't there something else which needs to be done?
