### ISSUE TITLE
Hostname overloads for server bindings

### ISSUE THREAD

**Issue by carbotaniuman** [http4k/http4k#531]
If this is possible, I'd like the ability to specify a hostname for a server so I dont have to copy and paste the classes myself. (And also so I can be generic)

**Comment by daviddenton** [comment]
Not really clear on what yours like to do here. Can you elaborate?

**Comment by carbotaniuman** [comment]
Binding to say 0.0.0.0 vs localhost only, for instance. Or listening on only one external IP.

**Comment by daviddenton** [comment]
We decided very specifically to avoid any kind of server Config wherever possible (due to the myriad of options available), but to make it easy and simple for people to write their own versions with the minimum amount of copied code. So from that perspective am afraid it’s a no. Making detailed generic interfaces (like a builder) is just not really worth it when people don’t really tend to change much and if they want custom configuration then they’ll already write their own serverconfig version anyway.

However, we are  very happy to accept PRs on how to reduce the boilerplate required by extracting common code from the various current Implementations (like the various handler classes that already exist).
