### ISSUE TITLE
OpenAPI3 contract rendering: support for "nullable": true in schema properties

### ISSUE THREAD

**Issue by usand** [http4k/http4k#539]
Hi,

Currently, optional Kotlin fields are rendered in the generated OpenAPI3 schema simply as non-required properties, i.e. they are left out of the "required" list. Marshaling such a field with a null value - rather than leaving the field out altogether - can cause problems for generated clients, since the _"nullable": true_ property is absent from the corresponding property in the schema.

Is there a way to have optional fields marked as _"nullable": true_ in the corresponding schema property? Perhaps there is some way to configure this, but I have been unable to find out how.

I have tried this with v3.280.0 and the org.http4k.format.Jackson module.

**Comment by daviddenton** [comment]
This is down to the configuration of the Jackson instance itself. If you just want to exclude null fields then you can achieve it by defining your own instance with the correct config. Like so...
```
object MyJackson : ConfigurableJackson(KotlinModule()
    .asConfigurable()
    .withStandardMappings()
    .done()
    .deactivateDefaultTyping()
    .setSerializationInclusion(JsonInclude.Include.NON_NULL)
    .configure(FAIL_ON_UNKNOWN_PROPERTIES, false)
    .configure(FAIL_ON_IGNORED_PROPERTIES, false)
    .configure(USE_BIG_DECIMAL_FOR_FLOATS, true)
    .configure(USE_BIG_INTEGER_FOR_INTS, true)
)
```
Note that you'll need to import the Body.auto lens from MyJackson in your endpoints (and use it to construct your OpenApi3 renderer).

For random questions like this, it's probably easier (and quicker) to seek help on our Slack channel. 😄

**Comment by usand** [comment]
This issue is with the http4k OpenAPI3 renderer not adding _nullable: true_ for optional Kotlin fields in the generated schema. It is not related to JSON serialization as such. I believe an optional field and a nullable field value are two distinct things; currently  only the former seems to be supported by the framework and perhaps that is by design.

Basically I'm looking for a way to achieve this in the generated contract:
https://swagger.io/docs/specification/data-models/data-types/#null
 
In any case, I'll check out the Slack channel. 😄

**Comment by daviddenton** [comment]
You won't be able to configure anything to add this - it will require a code change,

This is trivial to add if we equate optional to nullable, but I'm not sure if to apply it when the docs say:

`In objects, a nullable property is not the same as an optional property, but some tools may choose to map an optional property to the null value.`

In our case, we can't detect a difference between the 2 cases (ie we won't detect that a submitted value is null instead of missing).

**Comment by usand** [comment]
Obviously having this configurable would be useful - i.e. non-required (currently supported), nullable, or both.

It is arguably a bit odd that a Kotlin property that is nullable is not rendered as nullable in the generated schema. Is there a specific reason to choose to render nullable Kotlin properties as non-required rather than nullable in the schema?

Currently, it is **never possible** to return the following in a response body without breaking the generated contract:

```json
{
	"something": null
}
```

Perhaps everyone else is excluding null values from serialization and can thus be compliant - but this is not the default behaviour of the Jackson module, so I doubt that... 😄

**Comment by razvn** [comment]
Yes it's exactly what we did to avoid that. Create a custom Jackson that we pass to the renderer in order to have a error free yaml when exporting to the swagger editor.
If you don't have to edit I swaggerui does no complaint. So I guess most people didn't see the problem because they don't add it to the swagger editor. We do as unfortunately some descriptions are not generated by the code.
