### ISSUE TITLE
Publish 2.37.0

### ISSUE THREAD

**Issue by loganlinn** [http4k/http4k#62]
Documentation refers to version 2.37.0, but that doesn't appear to be available on Maven Central

**Comment by daviddenton** [comment]
Thanks for the report. :)

We generally suffer (as does everyone) from Maven central syncing being notoriously flakey and slow.. :) . We'll sort this out ASAP, but as a rule we generally add jCenter to our builds in order to ensure we can access artifacts earlier as bintray is much more reliable!

Unless you need the resilience4j integration or the undertow fix, 2.36.0 will be fine to use. 😀

**Comment by loganlinn** [comment]
No worries, I've already grabbed 2.36.0. Just wanted to let you know in
case it wasn't on your radar. Thanks for tip on bintray!
Cheers

**Comment by s4nchez** [comment]
@loganlinn 2.37.0 should be available now. Thank you for spotting it :)
