### ISSUE TITLE
Customizing the number of threads/cores used in the servers

### ISSUE THREAD

**Issue by lambrospetrou** [http4k/http4k#662]
Hello, I am happy user of http4k for a few years now (serverless mostly) but I wanted to raise this issue for discussion due to spending too much time last night on trying to figure this out.

I was looking into finding the number of threads/cores used by the [underlying backend servers](https://github.com/http4k/http4k/tree/master/http4k-server), e.g. Netty, Jetty, Apache, etc. I went through the whole of documentation but didn't find any reference to this. After going through the code of their implementation I could find that for Netty for example I can use the [system property `-Dio.netty.eventLoopThreads=N`](https://github.com/wusi05/netty-source-learning/blob/c026be1c41157d8a33dba7737e3fbdd5c87ddbba/netty-netty-4.1.15Final/transport/src/main/java/io/netty/channel/MultithreadEventLoopGroup.java#L41) to do that.

In the [Customise a Server Backend](https://www.http4k.org/guide/howto/customise_a_server_backend/) page and in [this Customisation](https://www.http4k.org/guide/reference/servers/#customisation) section, it is basically implied that due to the simplicity of the `ServerConfig` interface anyone wanting to do customisations can just copy one of the existing backend classes and modify the needed bits. I fully agree with your suggestion on this, for significant changes, but I think it would be useful if there were some knobs that we could configure even with the default implementations.

If not having a way to customise them, I would even find it very useful if there was at least some more documentation in the main [Server Backend](https://www.http4k.org/guide/reference/servers/) page with some details for each backend as provided by the default implementation. Maybe, even links to the corresponding backend servers configuration pages where we can find more information on what's supported to customise.

What do you think, would this something that fits into your vision, at least the documentation part?

**Comment by daviddenton** [comment]
TBH, we;re reluctant to do this for the very same reason that we stated in the docs. We don't want to become the repository for information which people should be getting from other places. 

The problem is that it's a slippery slope - having zero configuration and forcing people to look at/modify/reuse the (pretty simple and well factored) code is an absolutely concrete stance which frees us from that effort. At the end of the day, this project isn't about freeing people from having to think for themselves about the proper solution to their own situations. 😄 

Sorry to shut it down, but it's a hard no from us on this. 🙃 .

**Comment by lambrospetrou** [comment]
Understandable, thanks for the response anyway :)
