### ISSUE TITLE
Kotlinx serialization asJsonObject gives serialization exception

### ISSUE THREAD

**Issue by AndreVelde** [http4k/http4k#759]
I was trying to use asJsonObject with a list of string like so:
```
private fun buildFeature(id: String?, geometry: Geometry, stations: List<String>): Feature {
	val feature = Feature(geometry = geometry, id = id)

	if (stations.isNotEmpty()) {
		feature.setJsonProperty("stations", asJsonObject(stations))
		// feature.setJsonProperty("stations", stations.asJsonObject())
	}

	return feature
}
```

The issue is that asJsonObject gave the following error:
```
Request error kotlinx.serialization.SerializationException: Serializer for class 'ArrayList' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
    at kotlinx.serialization.internal.PlatformKt.serializerNotRegistered(Platform.kt:32)
    at kotlinx.serialization.SerializersKt__SerializersJvmKt.serializer(SerializersJvm.kt:59)
    at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
```

When I changed it to `Json.encodeToJsonElement(stations)` it works as expected without giving any errors.

Library version used: HTTP4K version 4.27.3.0

**Comment by daviddenton** [comment]
Because of the erased type of the class being accessed within the http4k JSON API (which takes Any in place of the raw list), I'm afraid I don't think this is possible to make work with the API (which is not relying on reified calls), so we currently cannot fix it. A workaround is to do:

```kotlin
KotlinxSerialization.json.encodeToJsonElement(listOf("hello", "world")
```

This will get you the ability to marshall as you need to whilst still having access to the custom mappings that the http4k module supports.
