### ISSUE TITLE
Unfilled placeholder in license

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#760]
https://github.com/http4k/http4k/blob/master/LICENSE#L189

There's a placeholder in the license that needs to be filled.  Or is this intentional and not an issue?  I only noticed because I'm considering migrating my own projects from The Unlicense to this same license.

```
Copyright {yyyy} {name of copyright owner}
```

**Comment by daviddenton** [comment]
I don't think it's an issue since Kotlin, Spring and Ktor all have the same placeholder.. 😉 

https://github.com/JetBrains/kotlin/blob/804eb61bf03ca10092e1ff19b995d9dfd862d181/license/LICENSE.txt
https://github.com/spring-projects/spring-framework/blob/c8648b523bbb94ee62427ef43fc4f018679431f6/LICENSE.txt#L190
https://github.com/ktorio/ktor/blob/main/LICENSE

**Comment by oharaandrew314** [comment]
Fair enough!
