### ISSUE TITLE
Moshi - Replace Kotlin-Reflect with kotlinx-metadata-jvm

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k#763]
Moshi has an [approved PR](https://github.com/square/moshi/pull/1183) that replaces kotlin-reflect with kotlinx-metadata-jvm; this PR was approved 2 years ago, but has sadly been left to rot.

This change would be nice because kotlin-reflect has grown to be bloated, and the much leaner kotlinx-metadata-jvm can get the same job done.  In serverless environments, every Megabyte helps, and this change saves 2.  In the meantime, the author has released [their own adapter](https://github.com/ZacSweers/MoshiX/tree/main/moshi-metadata-reflect), which continues to be maintained.  It's quite easy to integrate into http4k:

```kotlin
implementation("org.http4k:http4k-format-moshi") {
    exclude("org.jetbrains.kotlin", "kotlin-reflect")
}
implementation("dev.zacsweers.moshix:moshi-metadata-reflect:0.18.3")
```

```kotlin
object MoshiLite : ConfigurableMoshi(
    Moshi.Builder()
        .addLast(EventAdapter)
        .addLast(ThrowableAdapter)
        .addLast(ListAdapter)
        .addLast(MapAdapter)
        .also { it.asConfigurable().withStandardMappings() }
        .done()
)

fun Moshi.Builder.done(): Moshi.Builder = this
    .add(MetadataKotlinJsonAdapterFactory())
    .add(Unit::class.java, UnitAdapter)  // UnitAdapter is private, and must be copied or made public
```

This is a very simple change, so I don't know if it deserves to be merged into `http4k-format-moshi`, made into a new `http4k-format-moshi-lite` module, or just posted as a cookbook recipe.  There's also the matter that several other http4k modules directly depend on kotlin-reflect, such as `http4k-contract`.  If you wanted to eliminate kotlin-reflect, you could still use `http4k-contract` to share contracts, but you would be unable to generate an openapi spec.  Thoughts?

**Comment by daviddenton** [comment]
This is a really great find and definitely something which requires more investigation! :)

The claim seem to be that the metadata version of moshiX will replace kotlin-reflect - which would be amazing  - so I'm up for making that change in `http4k-format-moshi` if we believe that there are no other downsides - do we have any evidence either way?

A dream (of mine anyway) is to make `http4k-contract` have a Moshi/non-Jackson option with lightweight or zero reflection. In fact, since we are using `http4k-format-jackson` as a runtime dependency (and that already uses reflect), I've removed the API dependency on `kotlin-reflect` and it all builds ok so I've pushed that change. So we now have no direct dependencies on `kotlin-reflect` other than transitively through jackson and moshi and are one step closer to this. 🚀

**Comment by oharaandrew314** [comment]
It's working well on my small project, but I'll do some additional tests; including on android.  There's also been some buzz about `jackson-module-kotlin` [doing the same](https://github.com/FasterXML/jackson-module-kotlin/issues/450), but it seems like they're facing some architectural challenges 🙄 .

Can't really say why Moshi stalled on merging the PR.  The MoshiX author seems to believe [it will eventually be merged](https://github.com/ZacSweers/MoshiX/blob/main/moshi-metadata-reflect/README.md?plain=1#L6), but that was 2 years ago 🤷 .
