### ISSUE TITLE
Question: where can I find the source for generating an API from an OpenAPI spec?

### ISSUE THREAD

**Issue by gmulders** [http4k/http4k#766]
I tried to use the code generator online (https://toolbox.http4k.org/openapi), but it wasn't working (returned a 400). So I tried to find the sources and couln't find them. 

Question: where can I find the source for generating an API from an OpenAPI spec?

**Comment by daviddenton** [comment]
You actually can't I'm afraid. The toolbox is the one bit of http4k which isn't open source. Specifically for actually tracking down the error, can you share the open api file you were using? If it's the official Petstore YAML example, we do know that it actually isn't valid as it contains complex objects in a form body definition. 

The toolbox is totally stateless so we don't actually store the content that we parse. We should probably rework it so that it returns some type of error trace at some point. However it is quite a complex operation so errors tend to manifest as unreadable stack traces (which we can fix if it's a problem with interpreting the actual open api spec)

**Comment by gmulders** [comment]
Thank you for your quick reply!

I was indeed using the Petstore spec, I'll try some other spec.

Seems this issue can be closed. 😄
