### ISSUE TITLE
How to add audience form field on AccessTokenFetcher

### ISSUE THREAD

**Issue by 0xthc** [http4k/http4k#818]
Hello there !
I'm struggling to understand what would be the best way to add the audience form field from auth0 on the AccessTokenFetcher.
From what I understand auth0 sends back an opaque token by default unless you provide an audience parameter to the token endpoint (cf https://community.auth0.com/t/why-is-my-access-token-not-a-jwt-opaque-token/31028)
If I'm correct this parameter should be added in the AccesTokenFetcher fetch method but as the requestForm is implemented as https://github.com/http4k/http4k/blob/master/http4k-security/oauth/src/main/kotlin/org/http4k/security/OAuthWebForms.kt#L15-L24 I'm not sure if it is possible to add the parameter without rewriting the whole thing.
The workaround would be to hit the /userinfo endpoint with the opaque token but I was wondering if these kind of settings would belong into this library or if it is out of scope.
https://github.com/http4k/http4k/blob/master/http4k-security/oauth/src/main/kotlin/org/http4k/security/AccessTokenFetcher.kt#L34-L37

In any way thanks for the time and thanks for the awesome work it really is a pleasure working with http4k

**Comment by daviddenton** [comment]
It's very interesting because I came across exactly this problem this week. However, I couldn't' actually get auth0 to return me a JWT instead of the opaque token regardless of if I set the audience field. 

Regardless, I'm couldn't actually find anywhere in the specs where setting the audience field is specified so came to the conclusion that this is an Auth0 specific implementation... which was quite annoying because the spec is complicated enough already!

(Modifying of providing your own AccessTokenFetcher is the way to go for this BTW.)  😄
