### ISSUE TITLE
Does http4k have any benchmarks?

### ISSUE THREAD

**Issue by adam-arold** [http4k/http4k#83]
I've written about Kotlin HTTP libraries on [my blog](http://the-cogitator.com/2018/01/06/going-beyond-android-kotlin-on-the-backend.html#comment-3704374708) and someone mentioned http4k.
I looked at the [Techempower benchmarks](https://www.techempower.com/benchmarks/) but http4k was not present. Do you plan to write a benchmark for it or do you happen to have one now?
I'd like to see how http4k performs because the lib itself looks promising.

**Comment by adam-arold** [comment]
I've just checked the docs. Do you have the results of your benchmark or do I have to wait until Round 15 on Techempower?

**Comment by daviddenton** [comment]
We are actually enrolled for round 15, and are appearing in the previews https://www.techempower.com/benchmarks/previews/round15/#section=data-r15&hw=ph&test=json&l=xan3i7 . However, a couple of things with that:
1. We've had real problems with the database tests in their environment - so much so that we've pretty much given up on getting them working correctly. The servers just don't seem to start at all when they run it. We can't repro this locally.
2. Ditto for Netty with ALL of the TE test cases.

The sporadicness of the TE published results also doesn't help with the above - R14 was published in May 2017! If they ever get around to continuous benchmarking then we might go back and revisit, but at the moment life's too short to worry about it! :)

Apart from that, http4k *is* proven in production at significant scale - it's running all of the traffic for a top 900-ranked global site according to alexa.com - and that site is actually top 250 in China. The deployment environment for that site is a completely untuned Jetty running on CloudFoundry - it's microservices based so there are about 15 or so http4k services running behind the main site.

Any more questions, happy to answer them - we hang out on the Kotlin slack if you want to chat directly.
