### ISSUE TITLE
Can't upgrade Jetty version

### ISSUE THREAD

**Issue by sofiaspringer** [http4k/http4k#984]
Hello, the project I am working on depends both on http4k and jetty (which as you know is also a dependency of http4k). However, we are blocked from upgrading Jetty version to 12 because http4k most recent version still uses Jetty 11. Is there a new version of http4k using Jetty 12 being launched soon? 

Many Thanks

**Comment by daviddenton** [comment]
Unfortunately, Jetty 12 is almost a total rewrite of the Jetty 11 APIs and thus will require significant rework of the http4k code as well. Also, the migration docs aren't very informative (happy to be wrong on this if people have pointers!).

We do know about it but would appreciate any help to get the APIs migrated - it's definitely not a priority for us (especially because we personally tend to use Undertow as our server of choice :) )

**Comment by daviddenton** [comment]
it's what we did for apache 4-5, so that seems ok - however for that version we actually made the OLD one the versioned one and left new one to be without the number. I'd propose the same thing here, so we'd have:

http4k-server-jetty-11 (v11)
http4k-server-jetty (v12)

**Comment by FredNordin** [comment]
What happens when Jetty 13 is released? :grin:

**Comment by FredNordin** [comment]
Seriously though, the naming of the new modules is less of an issue and I would always favour consistency.

**Comment by daviddenton** [comment]
As long as the APIs are compatible, we've generally upgraded major versions silently (with a Semver bump of course) as it doesn't really affect the vast majority of users. eg. we went from jetty 8 -> 11 with no issues :)

**Comment by FredNordin** [comment]
I'm tempted to have a go... (famous last words)

**Comment by FredNordin** [comment]
So the module name of `org.eclipse.jetty:jetty-server` is still the same in version 12, which mean we won't be able to (AFAIK) have two versions defined in the `versions.properties` file for `refreshVersions` plugin. That means, unless we do something hacky, that having two modules targeting different versions of Jetty would be difficult.
Maybe just have to bite the bullet and upgrade Jetty to 12...

**Comment by daviddenton** [comment]
We might be able to work around that, so having a decent idea about the work involved in an upgrade would be helpful. J21 is out now, so (as soon as Helidon upgrades to it - the preview features flags from v20 are incompatible with v21! 🙄 ) we can actually bump the major version number, which would be a good time to upgrade to Jetty12 as well :)

**Comment by FredNordin** [comment]
What I'll do is to upgrade the dependencies for the server and client to 12 and then see what breaks.That should give us a fair idea of the impact. I would guess most things in the server, like HTTP and SSE handling, would break, as well as the client body handling, because that model has completely changed. That's what I get for contributing the client and SSE code in the past :laughing:

**Comment by FredNordin** [comment]
I've started work on the server side. Not too bad so far - just have to code to the Jetty API instead of the servlet API. That probably means that dependency (Servlet) can go from the project.

**Comment by FredNordin** [comment]
I've not had the time to work on this for a while, but I will continue today.

**Comment by daviddenton** [comment]
This is due for the next release (5.12.0.0), so am closing
